"""Frozen red-baseline test for implementer canary-001-bounded-null-check-fix.

Do not edit this file as part of the fix. It defines the exact required
behavior; the candidate must make `src/inventory_guard.py` satisfy it.
"""
import unittest

from src.inventory_guard import needs_reorder


class NeedsReorderTests(unittest.TestCase):
    """Pins the required behavior of `needs_reorder`."""

    def test_returns_true_when_quantity_at_threshold(self):
        self.assertTrue(needs_reorder(5, 5))

    def test_returns_false_when_quantity_above_threshold(self):
        self.assertFalse(needs_reorder(10, 5))

    def test_returns_true_when_quantity_is_none(self):
        # Unknown on-hand quantity must be treated as needing reorder
        # review, not raise TypeError. This is the failing (red) case
        # against the frozen buggy module.
        self.assertTrue(needs_reorder(None, 5))


if __name__ == "__main__":
    unittest.main()
